### ISSUE TITLE
The badge icon is pulled instead of the profile avatar

### ISSUE THREAD

**Issue by pavichokche** [Azland/Mini-Steam-Launcher#1] opened 2023-06-17 11:22 UTC
I'm not sure what the cause is, because with your [default] profile, your avatar shows up correctly.

![image](https://github.com/Azland/Mini-Steam-Launcher/assets/14185621/78242e63-fe0a-4bb8-8b02-a958b2968d86)

But with my profile I get the attached image as a result. I tried both of these and the results are the same:
https://steamcommunity.com/profiles/76561198007473670/
https://steamcommunity.com/id/pavichokche/

**Comment by pavichokche** [comment] 2023-06-17 11:44
I manually inserted my avatar URL into the script so it doesn't need to go looking for it. That said, it is pretty strange, looking at the page source, that it somehow is grabbing the badge icon based on the regular expression you have set up...

**Comment by Azland** [comment] 2023-06-17 14:31
Thanks for highlighting @pavichokche. 

I can see that this is caused by differences in our profiles, specifically Avatar borders. My profile has one, so I lazily grab the "next" element, otherwise it returns the border instead of the profile image. This doesn't work for profiles which don't have a border applied, such as your own.

I'll review and make this more selective.

**Comment by Azland** [comment] 2023-06-18 10:43
Resolved in the latest version: https://github.com/Azland/Mini-Steam-Launcher/releases/tag/4.0.1

**Closed as completed** 2023-06-18 10:42 UTC

**Comment by pavichokche** [comment] 2023-06-18 17:31
Right on! It works well now without the need for edits. However, for some reason the source code .zip and .tar in your 4.0.1 release are the April 12th ones, I don't know if that's normal.
